name: Jai Santoshi Maa
url: http://www.santoshimaa.org/
domain: www.santoshimaa.org

permalink: pretty

nav:
- text: Home
  url: /
- text: Description of Maa
  url: /description-of-maa/
- text: Vrat Vidhi
  url: /vrat-vidhi/
- text: Vrat Katha
  url: /vrat-katha/
- text: Aarti
  url: /aarti/
- text: Bhajans
  url: /bhajans/
- text: Movies
  url: /movies/
- text: Chalisa
  url: /chalisa/
- text: 108 Names
  url: /108-names/
- text: Photo Gallery
  url: /photo-gallery/
- text: Temples
  url: /temples/
- text: Events
  url: /events/
- text: Guest Book
  url: /guest-book/
- text: Contact Us
  url: /contact-us/

footer_links:
- url: http://www.jaisantoshimaa.com/
  text: jaisantoshimaa.com
- url: http://www.srijaisanthoshi.com/
  text: srijaisanthoshi.com
- url: http://www.jaisanthoshimata.com/
  text: jaisanthoshimata.com